name: Agents Talk

on:
  workflow_dispatch: {}

concurrency:
  group: ai-dashboard-talk
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci
      - name: Run talk (single-call, cached)
        run: npm run m8:talk-once
        continue-on-error: true
