name: Build data

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"   # 매 정시 (UTC)

permissions:
  contents: write   # GITHUB_TOKEN으로 커밋/푸시 허용

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (optional)
        run: npm ci || true

      - name: Generate data
        run: node scripts/generate_data.cjs

      - name: Commit & push data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "chore(data): refresh $(date -u +%F-%TZ)" || echo "no changes"
          git push
