name: M8 Fetch News
on:
  schedule:
    - cron: "0 0,12 * * *"   # UTC 00:00 / 12:00 (하루 2회)
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run m8:news
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/snapshots.json
          git commit -m "M8: update news snapshots [skip ci]" || echo "No changes"
          git push
