name: M9 GitHub Trends
on:
  schedule: [ { cron: "5 0,12 * * *" } ]
  workflow_dispatch: {}
permissions: { contents: write }
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci
      - run: npm run m9:github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/snapshots.json
          git commit -m "M9: update github trends [skip ci]" || echo "No changes"
          git push
